---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/seadogger/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - mas
  - packer
  - terraform

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - sequel-pro
  - sublime-text
  - vagrant
  - visual-studio-code
  - tigervnc-viewer
  - makemkv
  - plex-media-player
  - sketchup
#  - ubiquiti-unifi-controller  # Did not want to uninstall to get this working.
  - cleanmymac
  - java
#  - 8bitdo-firmware-updater
#  - canon-pixma-scanner-driver-ica

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 425264550, name: "Disk Speed Test (3.2)" }
  - { id: 463362050, name: "PhotoSweeper (3.5.0)" }
  - { id: 905384638, name: "FileBot.launcher (4.8.5)" }
  - { id: 462054704, name: "Microsoft Word (16.32)" }
  - { id: 462062816, name: "Microsoft PowerPoint (16.32)" }
  - { id: 462058435, name: "Microsoft Excel (16.32)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
